# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for PubNub MCP Server
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy source code
COPY index.js ./
COPY resources ./resources

# Ensure the entrypoint is executable
RUN chmod +x index.js

# Expose no ports (stdio-based)

# Default command
CMD ["node", "index.js"]
